apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ngnix.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: ingress-service
spec:
  rules:
    - host: www.denizgirginer8.xyz
      http:
        paths:
          - path: /api/orders/?(.*)
            backend:
              serviceName: orders-service
              servicePort: 3000
          - path: /api/users/?(.*)
            backend:
              serviceName: ticket-auth-service
              servicePort: 3000
          - path: /api/tickets/?(.*)
            backend:
              serviceName: tickets-service
              servicePort: 3000
          - path: /api/payments/?(.*)
            backend:
              serviceName: payments-service
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
    - host: denizgirginer8.xyz
      http:
        paths:
          - path: /api/orders/?(.*)
            backend:
              serviceName: orders-service
              servicePort: 3000
          - path: /api/users/?(.*)
            backend:
              serviceName: ticket-auth-service
              servicePort: 3000
          - path: /api/tickets/?(.*)
            backend:
              serviceName: tickets-service
              servicePort: 3000
          - path: /api/payments/?(.*)
            backend:
              serviceName: payments-service
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
          
          
